# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-16.04"
    config.ssh.forward_agent = true
    config.vm.define "db" do |db|
        db.vm.network "private_network", ip: "192.168.210.10"
        db.vm.network "forwarded_port", guest: 22, host: 2200, id: "ssh", disabled: true
        db.vm.network "forwarded_port", guest: 22, host: 21010
        db.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.cpus = "1"
        end
        db.vm.provision "shell" do |s|
            s.path = 'scripts/db.sh'
        end
    end
    config.vm.define "web" do |web|
        web.vm.network "private_network", ip: "192.168.210.20"
        web.vm.synced_folder "../trello-angularjs", "/var/trello-angularjs", nfs: true
        web.vm.network "forwarded_port", guest: 22, host: 2200, id: "ssh", disabled: true
        web.vm.network "forwarded_port", guest: 22, host: 21020
        web.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.cpus = "1"
        end
        web.vm.provision "shell" do |s|
            s.path = 'scripts/web.sh'
        end
    end
end
