# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-16.04"
    config.ssh.forward_agent = true
    config.vm.define "api" do |api|
        api.vm.network "private_network", ip: "192.168.210.10"
        api.vm.network "forwarded_port", guest: 22, host: 2200, id: "ssh", disabled: true
        api.vm.network "forwarded_port", guest: 22, host: 21010

        api.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.cpus = "1"
        end

        api.vm.provision "shell", inline: "sudo apt-get -y install puppet"

        api.vm.synced_folder "../../api", "/vagrant/api"

        api.vm.provision :puppet do |puppet|
            puppet.manifests_path = "puppet"
            puppet.manifest_file  = "manifests"
        end

        api.vm.provision "shell", inline: "sudo service nginx start", run: "always"
        api.vm.provision "shell", inline: "sudo systemctl restart api", run: "always"

    end
end
